### ISSUE TITLE
Handle /etc/timezone on Debian systems

### ISSUE THREAD

**Issue by gforcada** [geerlingguy/ansible-role-ntp#10]
Hi,

thanks for sharing this role!

It works perfectly fine, but I found that although the time is set correctly the timezone is not updated on ``/etc/timezone``.

Any reason not to do so?

I found that on a Ubuntu 16.04 server.

**Comment by geerlingguy** [comment]
Huh... TIL Debian works with timezones slightly different than RHEL (and, unless I'm missing something, [different than pretty much all other distros?](http://tldp.org/HOWTO/Clock-2.html)): https://wiki.debian.org/TimeZoneChanges

Debian wants the user to run `

And it looks like it definitely has an effect on Java SDKs (http://mail.openjdk.java.net/pipermail/core-libs-dev/2013-August/020229.html), and possibly cron (though I can't find definitive documentation for this). But most other things rely on `/etc/localtime` only...

I'm trying to figure out _why_ Debian doesn't seem to follow the general standard here, and what the real difference between the two files is, before blindly just changing both files to the same value (in case _there be dragons_).

**Comment by geerlingguy** [comment]
Also from [this answer](http://superuser.com/a/724497), it looks like the best way to set this non-interactively is:

```
echo "Europe/Zurich" > /etc/timezone 
dpkg-reconfigure -f noninteractive tzdata
```

**Comment by gforcada** [comment]
I noticed that because jenkins (created with geerlingguy.jenkins of course, thanks a lot for all these awesome ansible roles btw!!) was showing a different timezone than expected.

So at least for java in general or jenkins in particular it has some effects.

**Comment by geerlingguy** [comment]
Yeah, it seems since Jenkins uses Java, it inherits the strange (to me) use of `/etc/timezone` instead of `/etc/localtime` for the default TZ data (from [here](http://mail.openjdk.java.net/pipermail/core-libs-dev/2013-August/020229.html)):

  1. If TZ environment variable is set, use that.
  2. If `/etc/timezone` is readable, read the time zone from there.
  3. If `/etc/localtime` is a symlink, resolve that, and use the name to guess the time zone.
  4. Scan `/usr/share/zoneinfo` for a file whose contents match the contents of `/etc/localtime`.

**Comment by geerlingguy** [comment]
And it looks like on Debian systems, `/etc/timezone` is present, and as you mentioned, since it's not managed by this role, Java's not getting the configured timezone.

I'm testing a fix locally.

**Comment by geerlingguy** [comment]
I've pushed up a fix. If tests pass I'll tag a new release—it only makes this change/addition on Debian systems.

**Comment by gforcada** [comment]
Thanks!
