### ISSUE TITLE
Add handler to restart crond if timezone is changed.

### ISSUE THREAD

**Issue by ravishivt** [geerlingguy/ansible-role-ntp#15]
As per https://docs.ansible.com/ansible/timezone_module.html#synopsis, it is recommended to restart crond if the timezone is changed.

**Comment by geerlingguy** [comment]
I would love to do this—one caveat if adding a handler for this is that we would need to make either a variable/flag (and default to `false`) for `ntp_restart_crond` (or something like that), or we would need to detect whether cron is present on the system before restarting it (since many systems don't have cron running).

At an Ansible meetup tonight in St. Louis, someone else mentioned having the same issue, where cron jobs were running a few hours out of sync after using this role to set the timezone :)

**Comment by torrentalle** [comment]
The PR #60 should fix this issue, detecting running cron service and restarting when timezone changes

**Comment by glen-84** [comment]
Not stale.

**Comment by geerlingguy** [comment]
This has been fixed.

**Comment by geerlingguy** [comment]
(Will be in a 2.0.0 release).
