### ISSUE TITLE
Option to use systemd systemd-timesyncd

### ISSUE THREAD

**Issue by lathama** [geerlingguy/ansible-role-ntp#49]
TLDR
apt-get purge ntp
systemctl restart systemd-timesyncd.service
systemctl status systemd-timesyncd.service

https://lathama.net/Using_systemd_timesyn_on_Debian_Stretch

**Comment by agimenez** [comment]
Does it make sense in this role? Or should it go in another separate role? We'd have to parametrize out a lot of stuff, making it an effective role with 2 different sets of tasks (like, 2 different roles merged in a single one with conditional).

What do you think @geerlingguy? This role as-is does not work for Ubuntu >= 18.04 since timesyncd takes always precedence and ntpd does not even start.

**Comment by geerlingguy** [comment]
Hmm... I'm mixed on it. There's also a PR to add support for `chrony` on RHEL 7, and then this role would manage all three of `ntp`, `chrony`, and `timesync`... In the spirit of making things maintainable it seems like it would be better to have separate projects for each, especially since the actual configuration is drifting a bit between them.

**Comment by agimenez** [comment]
The downsides would be a lot of conditional stuff, but the upside would be that you wouldn't need to think about what role is the one your distro needs.

 _"RedHat? Then use geerlingguy.ntp. Wait, we are using RH7! Oh, yes, then we need geerlingguy.chrony. What about our Debian systems? Yeah, geerlingguy.ntp will work. No, wait, we have Ubuntu 18.04, Does it work on it? or we need to apply geerlingguy.timesyncd instead?"_

:)

**Comment by janorn** [comment]
I think it would be a great idea if this role actually could take into consideration to stop timesyncd as there would be issues running this role on a later versions of Ubuntu. A simple boolean.

disable_timesyncd = false

Set to true if you are sure you want to replace timesyncd with ntp.
